apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }

    my-hlf-domain.com:53 {
        errors
        cache 30
        forward . 8.8.8.8
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-18T12:09:38Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "229"
  uid: b87f9e33-3d49-4584-a3fd-c8303be3fc18
